[build]
  base = "client"
  command = "npm install --include=dev && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://book-library-management-system.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
